from typing import Any

from chromadb import CloudClient, Collection
from chromadb.api import ClientAPI
from chromadb.utils.embedding_functions import GoogleGenerativeAiEmbeddingFunction
from app.config import settings


def get_chroma_client() -> ClientAPI:
    client = CloudClient(
        api_key=settings.chromadb_api_key,
        tenant="658726cb-7a81-4f8e-999a-a2b60e97b57d",
        database="Dev",
    )
    return client


def get_embedding_function() -> GoogleGenerativeAiEmbeddingFunction:
    return GoogleGenerativeAiEmbeddingFunction(
        model_name="models/gemini-embedding-001",
        task_type="RETRIEVAL_DOCUMENT",
        api_key=settings.gemini_api_key,
    )


def get_or_create_collection(client: ClientAPI, collection_name: str) -> Collection:
    embedding_function = get_embedding_function()
    try:
        collection = client.get_collection(
            name=collection_name,
            embedding_function=embedding_function,
        )
    except Exception:
        collection = client.create_collection(
            name=collection_name,
            embedding_function=embedding_function,
        )
    return collection


def add_documents_to_collection(
    collection: Collection,
    documents: list[str],
    metadatas: list[dict[str, Any]],
    ids: list[str],
) -> None:
    """Add documents to collection - embeddings will be generated by the collection's embedding function."""
    collection.add(
        documents=documents,
        metadatas=metadatas,
        ids=ids,
    )


def query_collection_by_text(
    collection: Collection,
    query_texts: list[str],
    n_results: int = 5,
) -> dict[str, Any]:
    """Query collection with text - embeddings will be generated by the collection's embedding function."""
    results = collection.query(
        query_texts=query_texts,
        n_results=n_results,
    )
    return dict(results)
